services:
  redis:
    image: redis:latest
    container_name: sr_redis
    ports:
      - 6379:6379
    volumes:
      - sr_redis_data:/data
    networks:
      - spring_redis_network
  redisinsight:
    container_name: sr_redisinsight
    depends_on:
      - redis
    image: redis/redisinsight:latest
    ports:
      - 8282:5540
    volumes:
      - sr_redis_redisinsight:/data
    networks:
      - spring_redis_network
  db:
    image: mariadb:latest
    container_name: sr_mariadb
    restart: always
    volumes:
      - sr_db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      MYSQL_PASSWORD: sr-pass
      MYSQL_USER: sr-user
      MYSQL_DATABASE: db_sr
    ports:
      - 3366:3306
    networks:
      - spring_redis_network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: sr_phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - spring_redis_network
networks:
  spring_redis_network:
volumes:
  sr_db_data:
  sr_redis_data:
  sr_redis_redisinsight: